services:
  oracle-db:
    # Imagem de desenvolvimento do Oracle Database XE. Leve e rápida.
    image: gvenzl/oracle-xe:21-slim-faststart
    container_name: gestao_db_oracle
    environment:
      # A senha para os usuários SYS, SYSTEM e PDBADMIN.
      ORACLE_PASSWORD: oracle
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
    networks:
      - gestao_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gestao_api
    # Comando para produção: sem reload automático
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    # As variáveis de ambiente devem ser gerenciadas por um arquivo .env no servidor
    # Exemplo: DATABASE_URL=postgresql://postgres:postgres@postgres:5432/gestao_fornecedores
    # Para Oracle: DATABASE_URL=oracle+oracledb://system:oracle@oracle-db:1521/XE
    env_file:
      - ./backend/.env
    depends_on:
      - oracle-db
    # Em produção, o código é copiado para a imagem durante o build, não montado por volume.
    # volumes:
    #   - ./backend:/app
    networks:
      - gestao_network
      

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gestao_frontend
    # Comando para produção: serve os arquivos estáticos gerados pelo 'npm run build' (do Vite)
    command: serve -s dist -l 3000
    ports:
      - "3000:3000"
    # A variável de ambiente para a URL da API é lida de um arquivo .env
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    # Em produção, o código é copiado para a imagem, não montado por volume.
    # volumes:
    #   - ./frontend:/app
    networks:
      - gestao_network

volumes:
  oracle_data:

networks:
  gestao_network:
    driver: bridge
